language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI Server의 Home
cache:
  directories:
    - '&HOME/.m2/repository'
    - '&HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springbootstudy *
  - mkdir -p deploy
  - mv springbootstudy.zip deploy/springbootstudy.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: song-springbootstudy-build
    region: us-east-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: song-springbootstudy-build
    key: springbootstudy.zip
    bundle_dype: zip
    application: springbootstudy-CodeDeploy
    deployment_group: springboot-deploy
    region: us-east-2
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ggp04114@naver.com

